RegisterNetEvent('nhr_dispatch:client:alert', function(title, message, coords)
    lib.notify({ title = title, description = message, duration = 8000 })
    local blip = AddBlipForRadius(coords.x, coords.y, coords.z, 70.0)
    SetBlipColour(blip, 1) SetBlipAlpha(blip, 130)
    CreateThread(function() Wait(60000) RemoveBlip(blip) end)
end)
exports('SendAlert', function(service, title, message)
    local coords = GetEntityCoords(PlayerPedId())
    TriggerServerEvent('nhr_dispatch:server:alert', service, title, message, { x=coords.x,y=coords.y,z=coords.z })
end)
